simulation:
  duration: 30
  speed: 0.3
  dropPosition: [-4, 30]
  maxNumberOfRocks: 52

gameConstants:
  hikerConstants:
    hikerMaxHealth: 100
    spawnXRelativeToScreenWidth: 0.4
    hikerHeight: 1.8
    hikerWidth: 1.15
    crouchedHikerHeight: 1.42
    crouchedHikerWidth: 0.96
    mass: 800.0
    duckSpeedFactor: 0.35
    normalSpeed: 2.6
    maxSpeed: 8.0 # Make sure this times airMovementSpeedFactor is higher than maxKillBarFactor * killBarBaseVelocity
    jumpVelocity: 10.0
    airMovementSpeedFactor: 0.77
    maxSpeedNegSlope: 5.0
    maxClimbableSlope: 4.0
    knockbackIntensity: 0.5 # between 0 and 1
    knockbackLossPerStep: 0.25 # between 0 and 1
    knockbackCutoff: 5

  itemsConstants:
    spawnItems: true
    shieldTime: 15.0
    collectionRadius: 1.0
    slotsPerInventory: 3
    itemsPerSlot: 64
    kaiserschmarrnHealthRestoration: 30
    coinScore: 500
    coinAccelerationFactor: 0.05
    startSpawnTime: 5.0
    minSpawnTime: 2
    maxSpawnTime: 10
    itemBaseHeight: 1
    itemMaxHeight: 2.6
    itemsPerSecond: 0.05
    inventorySlotSize: 80.0

  rockConstants:
    spawnRocks: false
    minRockSize: 0.32
    maxRockSize: 1.0
    minSpawnLinearMomentum: 0.01
    maxSpawnLinearMomentum: 10.0
    minSpawnAngularMomentum: 0.1
    maxSpawnAngularMomentum: 1.0
    spawnOffsetX: 0.5
    minRockDensity: 1.0
    maxRockDensity: 3.0

  physicsConstants:
    gravitationalConstant: -9.81
    gravitySpinEffectOnVertices: 0.01
    epsilon: 0.01 # should be "small"
    rockRockBounciness: 0.4 # between 0 and 1 (wink wink*)
    rockTerrainBounciness: 0.8 #between 0 and 1 (wink wink*)
    physicsDeltaT: 0.01 # ideally, 1/physicsDeltaT >> frameRate
    maxNumberOfResolutionSteps: 4
    maxNumberOfPhysicsStepsPerFrame: 4
    terrainSubstepSize: 0.25 # between 0 and 1 (no seriously this time)
    rockSubstepSize: 0.25 # between 0 and 1 (no seriously this time)
    debugCDRendering: false
    #staticFriction: 0.8
    #dynamicFriction: 0.4

  inputConstants:
    maxGamepads: 8
    gamepadItemSwitchCooldown: 0.1
    gamepadInitializingTime: 3
    itemSwitchThreshold: 0.5

  visualConstants:
    uiMargin: 20
    fontSizeScore: 30
    fontSizeAltimeter: 20
    healthBarWidth: 200
    healthBarHeight: 20
    positionToScoreRatio: 10
    altimeterSteps: 10
    rumbleIntensity: 0.4
    rumbleDampening: 0.9
    backgroundDistanceScale: 0.1
    cameraToHikerOffset: 1
    mountainGradientHeight: 300
    mountainResolution: 10
    shakeEnabled: false
    renderPhysicsStepSize: true

  audioConstants:
    musicEnabled: true
    musicVolume: 0.3
    effectsThreshold: 35

  barriersConstants:
    killBarBaseVelocity: 0.0
    killBarAccelerationFactor: 0.015 # describes how quickly the killbar accelerates with an increasing right border
    maxKillBarFactor: 4.0 # => max killbar velocity is base velocity * max factor
    playerRightBarrierOffset: 15.0
    monsterXRelativeToScreenWidth: 0.1
    monsterHeight: 3.6
    monsterWidth: 2.875

  terrainConstants:
    bufferLeft: 25.0
    bufferRight: 50.0
    biomeWidth: 100.0

    renderingResolution: 0.1
    collisionDetectionResolution: 1
    collisionDetectionPreFilteringTolerance: 0.2

    generationCheckingRange: 5.0
    minimalBasePointDistance: 1.0
    minimalBasePolylineAngle: 30.0 #in degrees
    maximalSlopeHikerClearance: 85.0 #in degrees
    hikerClearanceTolerance: 1.5 #multiplier for hiker width and height
    maximalOverhangDepth: 7.0
    maximalOverhangHeight: 5.0

  rockSpawnerConstants:
    # All based on difficulty [EEEASY, EASY, MEDIUM, HARD, I_WANT_MOMY]
    linearMomentumDifficultyFactor: [ 0.0, 0.25, 0.5, 0.75, 1.0 ]
    spawningPhase: [ 60.0, 150.0, 250.0, 500.0, 1000.0 ]
    rockSpawnTimeInterval: [ 8.0, 7.0, 5.0, 3.0, 2.0 ]

    # Based on rock type
    rockTypePhase: [ 30.0, 40.0, 50.0, 60.0, 70.0, 80.0 ]



# flat, exponential steps
# ground-points: [[-100, 0], [-20, 0], [-10,0], [-5, 0], [-1, 0], [-0.5, 0], [0, 0], [0.5, 0], [1, 0], [5, 0], [10, 0], [20, 0], [100, 0]]

# flat small steps
#ground-points: [[-30, 0],[-29, 0],[-28, 0],[-27, 0],[-26, 0],[-25, 0],[-24, 0],[-23, 0],[-22, 0],[-21, 0],[-20, 0],[-19, 0],[-18, 0],[-17, 0],[-16, 0],[-15, 0],[-14, 0],[-13, 0],[-12, 0],[-11, 0],[-10, 0],[-9, 0],[-8, 0],[-7, 0],[-6, 0],[-5, 0],[-4, 0],[-3, 0],[-2, 0],[-1, 0],[0, 0],[1, 0],[2, 0],[3, 0],[4, 0],[5, 0],[6, 0],[7, 0],[8, 0],[9, 0],[10, 0],[11, 0],[12, 0],[13, 0],[14, 0],[15, 0],[16, 0],[17, 0],[18, 0],[19, 0],[20, 0],[21, 0],[22, 0],[23, 0],[24, 0],[25, 0],[26, 0],[27, 0],[28, 0],[29, 0],[30, 0]]

# buggy hill
#ground-points: [[-100, 0], [-10, 0], [0, 7], [3, 7], [4.7, 7], [7, 5], [9, 5],  [10, 4.2], [5.5, 4], [7.5, 3], [8, 2], [9, 1], [10, 0], [20, 0]]

# buggy 2
# ground-points: [[-100, 0], [0, 0], [2.6, 1.6], [2.7, -2.25], [10, 0], [100, 0]]

# inverse triangle
#ground-points: [[-30, 30], [-29, 29], [-28, 28], [-27, 27], [-26, 26], [-25, 25], [-24, 24], [-23, 23], [-22, 22], [-21, 21], [-20, 20], [-19, 19], [-18, 18], [-17, 17], [-16, 16], [-15, 15], [-14, 14], [-13, 13], [-12, 12], [-11, 11], [-10, 10], [-9, 9], [-8, 8], [-7, 7], [-6, 6], [-5, 5], [-4, 4], [-3, 3], [-2, 2], [-1, 1], [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10], [11, 11], [12, 12], [13, 13], [14, 14], [15, 15], [16, 16], [17, 17], [18, 18], [19, 19], [20, 20], [21, 21], [22, 22], [23, 23], [24, 24], [25, 25], [26, 26], [27, 27], [28, 28], [29, 29], [30, 30]]

# simple bowl
#ground-points: [[-30, 100], [-29, 95], [-28, 90], [-27, 85], [-26, 80], [-25, 75], [-24, 70], [-23, 65], [-22, 60], [-21, 55], [-20, 50], [-19, 45], [-18, 40], [-17, 35], [-16, 30], [-15, 25], [-14, 20], [-13, 15], [-12, 10], [-11, 5], [-10, 0], [-9, 0], [-8, 0], [-7, 0], [-6, 0], [-5, 0], [-4, 0], [-3, 0], [-2, 0], [-1, 0], [0, 0], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [6, 0], [7, 0], [8, 0], [9, 0], [10, 0], [11, 5], [12, 10], [13, 15], [14, 20], [15, 25], [16, 30], [17, 35], [18, 40], [19, 45], [20, 50], [21, 55], [22, 60], [23, 65], [24, 70], [25, 75], [26, 80], [27, 85], [28, 90], [29, 95], [30, 100]]

# quadratic bowl
#ground-points: [[-25, 100], [-24, 92.16], [-23, 84.64], [-22, 77.44], [-21, 70.56], [-20, 64.00], [-19, 57.76], [-18, 51.84], [-17, 46.24], [-16, 40.96], [-15, 36.00], [-14, 31.36], [-13, 27.04], [-12, 23.04], [-11, 19.36], [-10, 16.00], [-9, 12.96], [-8, 10.24], [-7, 7.84], [-6, 5.76], [-5, 4.00], [-4, 2.56], [-3, 1.44], [-2, 0.64], [-1, 0.16], [0, 0], [1, 0.16], [2, 0.64], [3, 1.44], [4, 2.56], [5, 4.00], [6, 5.76], [7, 7.84], [8, 10.24], [9, 12.96], [10, 16.00], [11, 19.36], [12, 23.04], [13, 27.04], [14, 31.36], [15, 36.00], [16, 40.96], [17, 46.24], [18, 51.84], [19, 57.76], [20, 64.00], [21, 70.56], [22, 77.44], [23, 84.64], [24, 92.16], [25, 100]]

# quadratic bowl
#ground-points: [ [ -25, 100 ], [ -24, 92.16 ], [ -23, 84.64 ], [ -22, 77.44 ], [ -21, 70.56 ], [ -20, 64.00 ], [ -19, 57.76 ], [ -18, 51.84 ], [ -17, 46.24 ], [ -16, 40.96 ], [ -15, 36.00 ], [ -14, 31.36 ], [ -13, 27.04 ], [ -12, 23.04 ], [ -11, 19.36 ], [ -10, 16.00 ], [ -9, 12.96 ], [ -8, 10.24 ], [ -7, 7.84 ], [ -6, 5.76 ], [ -5, 4.00 ], [ -4, 2.56 ], [ -3, 1.44 ], [ -2, 0.64 ], [ -1, 0.16 ], [0, 0], [ 1, 0.16 ], [ 2, 0.64 ], [ 3, 1.44 ], [ 4, 2.56 ], [ 5, 4.00 ], [ 6, 5.76 ], [ 7, 7.84 ], [ 8, 10.24 ], [ 9, 12.96 ], [ 10, 16.00 ], [ 11, 19.36 ], [ 12, 23.04 ], [ 13, 27.04 ], [ 14, 31.36 ], [ 15, 36.00 ], [ 16, 40.96 ], [ 17, 46.24 ], [ 18, 51.84 ], [ 19, 57.76 ], [ 20, 64.00 ], [ 21, 70.56 ], [ 22, 77.44 ], [ 23, 84.64 ], [ 24, 92.16 ], [ 25, 100 ] ]
#[ -0.3, 0 ], [ -3, -3 ], [ 0, -3 ], [ 3, -3 ], [ 0.3, 0 ]

# wide quadratic bowl
ground-points: [[-35, 50.0], [-34, 47.04], [-33, 44.16], [-32, 41.36], [-31, 38.64], [-30, 36.0], [-29, 33.44], [-28, 30.96], [-27, 28.56], [-26, 26.24], [-25, 24.0], [-24, 21.84], [-23, 19.76], [-22, 17.76], [-21, 15.84], [-20, 14.0], [-19, 12.24], [-18, 10.56], [-17, 8.96], [-16, 7.44], [-15, 6.0], [-14, 4.64], [-13, 3.36], [-12, 2.16], [-11, 1.04], [-10, 0.0], [-9, 0.04], [-8, 0.16], [-7, 0.36], [-6, 0], [-5, 0], [-4, 0], [-3, 0], [-2, 0], [-1, 0], [0, 0], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [6, 0], [7, 0.36], [8, 0.16], [9, 0.04], [10, 0.0], [11, 1.04], [12, 2.16], [13, 3.36], [14, 4.64], [15, 6.0], [16, 7.44], [17, 8.96], [18, 10.56], [19, 12.24], [20, 14.0], [21, 15.84], [22, 17.76], [23, 19.76], [24, 21.84], [25, 24.0], [26, 26.24], [27, 28.56], [28, 30.96], [29, 33.44], [30, 36.0], [31, 38.64], [32, 41.36], [33, 44.16], [34, 47.04], [35, 50.0]]