gameConstants:
  hikerConstants:
    hikerMaxHealth: 100
    spawnXRelativeToScreenWidth: 0.4
    hikerHeight: 1.8
    hikerWidth: 1.15
    crouchedHikerHeight: 1.42
    crouchedHikerWidth: 0.96
    mass: 800.0
    duckSpeedFactor: 0.35
    normalSpeed: 2.6
    maxSpeed: 8.0 # Make sure this times airMovementSpeedFactor is higher than maxKillBarFactor * killBarBaseVelocity
    jumpVelocity: 10.0
    airMovementSpeedFactor: 0.77
    maxSpeedNegSlope: 5.0
    maxClimbableSlope: 4.0
    knockbackIntensity: 0.5 # between 0 and 1
    knockbackLossPerStep: 0.25 # between 0 and 1
    knockbackCutoff: 5

  itemsConstants:
    spawnItems: true
    shieldTime: 15.0
    collectionRadius: 1.0
    slotsPerInventory: 3
    itemsPerSlot: 64
    kaiserschmarrnHealthRestoration: 30
    coinScore: 500
    coinAccelerationFactor: 0.05
    startSpawnTime: 5.0
    minSpawnTime: 2
    maxSpawnTime: 10
    itemBaseHeight: 1
    itemMaxHeight: 2.6
    itemsPerSecond: 0.05
    inventorySlotSize: 80.0

  rockConstants:
    spawnRocks: false
    minRockSize: 0.32
    maxRockSize: 1.0
    minSpawnLinearMomentum: 0.01
    maxSpawnLinearMomentum: 10.0
    minSpawnAngularMomentum: 0.1
    maxSpawnAngularMomentum: 1.0
    spawnOffsetX: 0.5
    minRockDensity: 1.0
    maxRockDensity: 3.0

  physicsConstants:
    gravitationalConstant: -9.81
    gravitySpinEffectOnVertices: 0.1
    epsilon: 0.01 # should be "small"
    rockRockBounciness: 0.4 # between 0 and 1 (wink wink*)
    rockTerrainBounciness: 0.9 #between 0 and 1 (wink wink*)
    physicsDeltaT: 0.01 # ideally, 1/physicsDeltaT >> frameRate
    maxNumberOfResolutionSteps: 4
    terrainSubstepSize: 0.5 # between 0 and 1 (no seriously this time)
    rockSubstepSize: 0.5 # between 0 and 1 (no seriously this time)
    debugCDRendering: true

  inputConstants:
    maxGamepads: 8

  visualConstants:
    uiMargin: 20
    fontSizeScore: 30
    fontSizeAltimeter: 20
    healthBarWidth: 200
    healthBarHeight: 20
    positionToScoreRatio: 10
    altimeterSteps: 10
    rumbleIntensity: 0.4
    rumbleDampening: 0.9
    backgroundDistanceScale: 0.1
    cameraToHikerOffset: 1
    mountainGradientHeight: 300
    mountainResolution: 10
    shakeEnabled: false

  audioConstants:
    musicEnabled: true
    musicVolume: 0.3
    effectsThreshold: 35

  barriersConstants:
    killBarBaseVelocity: 0.0
    killBarAccelerationFactor: 0.015 # describes how quickly the killbar accelerates with an increasing right border
    maxKillBarFactor: 4.0 # => max killbar velocity is base velocity * max factor
    playerRightBarrierOffset: 15.0
    monsterXRelativeToScreenWidth: 0.1
    monsterHeight: 3.6
    monsterWidth: 2.875

  terrainConstants:
    bufferLeft: 25.0
    bufferRight: 50.0
    biomeWidth: 100.0

    renderingResolution: 0.1
    collisionDetectionResolution: 1
    collisionDetectionPreFilteringTolerance: 0.2

    generationCheckingRange: 5.0
    minimalBasePointDistance: 1.0
    minimalBasePolylineAngle: 30.0 #in degrees
    maximalSlopeHikerClearance: 85.0 #in degrees
    hikerClearanceTolerance: 1.5 #multiplier for hiker width and height
    maximalOverhangDepth: 7.0
    maximalOverhangHeight: 5.0

  rockSpawnerConstants:
    # All based on difficulty [EEEASY, EASY, MEDIUM, HARD, I_WANT_MOMY]
    linearMomentumDifficultyFactor: [ 0.0, 0.25, 0.5, 0.75, 1.0 ]
    spawningPhase: [ 60.0, 150.0, 250.0, 500.0, 1000.0 ]
    rockSpawnTimeInterval: [ 8.0, 7.0, 5.0, 3.0, 2.0 ]

    # Based on rock type
    rockTypePhase: [ 30.0, 40.0, 50.0, 60.0, 70.0, 80.0 ]
