//
// Created by felix-roehr on 5/4/24.
//

#ifndef SURVIVING_SARNTAL_AXISMODIFICATION_H
#define SURVIVING_SARNTAL_AXISMODIFICATION_H

enum AxisModification { INCREASE, DECREASE, NO_MODIFICATION };

#endif // SURVIVING_SARNTAL_AXISMODIFICATION_H
