//
// Created by felix-roehr on 5/13/24.
//

#ifndef SURVIVING_SARNTAL_DEVICE_H
#define SURVIVING_SARNTAL_DEVICE_H

enum Device { DEVICE_KEYBOARD, DEVICE_GAMEPAD, DEVICE_MOUSE, DEVICE_NONE };

#endif // SURVIVING_SARNTAL_DEVICE_H
