soundEffects:
  background_music: "../assets/audio/background_music.mp3"
  background_music2: "../assets/audio/background_music2.wav"
  boom: "../assets/audio/boom.wav"
  cool_sound: "../assets/audio/cool_sound.mp3"
  duck: "../assets/audio/duck.wav"
  dudum: "../assets/audio/dudum.wav"
  error: "../assets/audio/error.wav"
  fart: "../assets/audio/fart.wav"
  game_over: "../assets/audio/game_over.wav"
  gameover: "../assets/audio/gameover.wav"
  jump: "../assets/audio/jump.wav"
  mepmep: "../assets/audio/mepmep.wav"
  ohje: "../assets/audio/ohje.wav"
  oof: "../assets/audio/oof.wav"
  pickup: "../assets/audio/pickup.wav"
  pipe: "../assets/audio/pipe.wav"
  proper_coin: "../assets/audio/proper_coin.wav"
  proper_crouch: "../assets/audio/proper_crouch.wav"
  proper_jump: "../assets/audio/proper_jump.wav"
  proper_rock_smash: "../assets/audio/proper_rock_smash.wav"
  shutdown: "../assets/audio/shutdown.wav"

textures:
  crouch: "../assets/texture/player_duck.png"
  jump: "../assets/texture/player_jump.png"
  walk: "../assets/texture/player_walk.png"
  Kaiserschmarrn: "../assets/texture/kaiserschmarrn.png"
  Coin: "../assets/texture/coin.png"
  Duck: "../assets/texture/duck.png"
  rock: "../assets/texture/stone.png"
  explosion: "../assets/texture/explosion.png"
  helicopter: "../assets/texture/helicopter.png"
  monster: "../assets/texture/killbar.png"
  midground: "../assets/layers/glacial_mountains.png"
  foreground: "../assets/layers/clouds_mg_1.png"
  mountain: "../assets/layers/mountain.png"