soundEffects:
  background-music: "../../assets/audio/background_music.mp3"
  background-music2: "../../assets/audio/background_music2.wav"
  use-kaiserschmarrn: "../../assets/audio/cool_sound.mp3"
  use-duck: "../../assets/audio/duck.wav"
  use-coin: "../../assets/audio/proper_coin.wav"
  pickup-item: "../../assets/audio/pickup.wav"
  crouch: "../../assets/audio/proper_crouch.wav"
  jump: "../../assets/audio/proper_jump.wav"
  rock-smash: "../../assets/audio/proper_rock_smash.wav"
  boom: "../../assets/audio/boom.wav"
  dudum: "../../assets/audio/dudum.wav"
  error: "../../assets/audio/error.wav"
  fart: "../../assets/audio/fart.wav"
  mepmep: "../../assets/audio/mepmep.wav"
  ohje: "../../assets/audio/ohje.wav"
  cool-sound: "../../assets/audio/cool_sound.mp3"
  oof: "../../assets/audio/oof.wav"
  pipe: "../../assets/audio/pipe.wav"
  meme-jump: "../../assets/audio/jump.wav"
  game-over: "../../assets/audio/game_over.wav"
  meme-game-over: "../../assets/audio/gameover.wav"
  meme-game-over2: "../../assets/audio/shutdown.wav"

textures:
  crouch: "../../assets/texture/player_duck.png"
  jump: "../../assets/texture/player_jump.png"
  walk: "../../assets/texture/player_walk.png"
  kaiserschmarrn: "../../assets/texture/kaiserschmarrn.png"
  coin: "../../assets/texture/coin.png"
  duck: "../../assets/texture/duck.png"
  rock: "../../assets/texture/stone.png"
  explosion: "../../assets/texture/explosion.png"
  helicopter: "../../assets/texture/helicopter.png"
  monster: "../../assets/texture/killbar.png"
  midground: "../../assets/layers/glacial_mountains.png"
  foreground: "../../assets/layers/clouds_mg_1.png"
  mountain: "../../assets/layers/mountain.png"
  rockRectangle: "../../assets/texture/rock.png"

items:
  kaiserschmarrn:
    typeId: 0
    autoCollect: false
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 5
  coin:
    typeId: 1
    autoCollect: true
    useOnPickUp: true
    dropOnUse: true
    spawnWeight: 3
  duck:
    typeId: 2
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 2

landmarks:
  - name: "Statue of Liberty"
    height: 93
  - name: "Big Ben"
    height: 96
  - name: "Eiffel Tower"
    height: 300
  - name: "Mount Everest"
    height: 8849

gameConstants:
  hikerConstants:
    hikerMaxHealth: 100
    hikerHeight: 140.0
    hikerWidth: 90.0
    crouchedHikerHeight: 110.0
    crouchedHikerWidth: 75.0
    duckSpeedFactor: 0.35
    normalSpeed: 260.0
    jumpVelocity: 750.0
    airMovementSpeedFactor: 0.6
    knockBack: 0.00005
    minSpeedNegSlope: 0.6
    maxSpeedNegSlope: 1.5
    minSpeedPosSlope: 0.5
    slowestNegSlope: -1.0
    fastestNegSlope: -0.5
    slowestPosScope: 2.0
    maxClimbableSlope: 4.0

  itemsConstants:
    collectionRadius: 110.0
    slotsPerInventory: 3
    itemsPerSlot: 64
    kaiserschmarrnHealthRestoration: 30
    coinScore: 500
    startSpawnTime: 5.0
    minSpawnTime: 2
    maxSpawnTime: 10
    itemBaseHeight: 80.0
    itemMaxHeight: 200.0
    itemsPerSecond: 0.05
    inventorySlotSize: 80.0

  rockConstants:
    minRockSize: 25.0
    maxRockSize: 75.0
    velocityCap: 1200.0
    gamma: 50.0
    maxAngularVelocity: 1000.0
    minSpawnVelocity: 1.0
    maxSpawnVelocity: 1000.0
    minSpawnRotationVelocity: 0.1
    maxSpawnRotationVelocity: 100.0
    rockTimePeriodDifficult: 1.0
    rockTimePeriodMedium: 5.0
    rockTimePeriodEasy: 2.0
    timeBetweenRockSpawns: 5.0
    numOfRocksToSpawn: 10
    spawnOffsetX: 50.0

  physicsConstants:
    gravitationalConstant: -1000.0
    epsilon: 0.001
    rockTerrainDamping: 0.8
    physicsDeltaT: 0.01

  inputConstants:
    maxGamepads: 8

  visualConstants:
    uiMargin: 20
    fontSizeScore: 30
    fontSizeAltimeter: 20
    healthBarWidth: 200
    healthBarHeight: 20
    positionToScoreRatio: 10
    altimeterSteps: 10
    rumbleIntensity: 0.4
    rumbleDampening: 0.9
    textureMidScale: 5.0
    textureForeScale: 7.0
    cameraToHikerOffset: 100
    mountainGradientHeight: 300
    mountainResolution: 10

  barriersConstants:
    killBarVelocity: 100.0
    playerRightBarrierOffset: 1280.0

  mountainConstants:
    visibleChunksCount: 16
    chunkBufferLeft: 2
    chunkBufferRight: 16
    initialHeight: 0
    slope: 0.4
    randomness: 1.0
    linStepSize: 0.5

  terrainConstants:
    bufferLeft: 500.0
    bufferRight: 500.0
    biomeWidth: 10000.0

    renderingResolution: 2.0
    collisionDetectionResolution: 10.0

    generationCheckingRange: 500.0
    minimalBasePointDistance: 100.0
    minimalBasePolylineAngle: 30.0 #in degrees
    maximalSlopeHikerClearance: 85.0 #in degrees
    hikerClearanceTolerance: 1.5 #multiplier for hiker width and height