run-dev-mode: false # if true the manual tests will run instead of the normal game
fullscreen: false

music:
  background-music: "../../assets/audio/happy-funny-kids.mp3"
  background-music2: "../../assets/audio/background_music2.wav"

soundEffects:
  use-kaiserschmarrn: "../../assets/audio/cool_sound.mp3"
  use-duck: "../../assets/audio/duck.wav"
  use-coin: "../../assets/audio/proper_coin.wav"
  pickup-item: "../../assets/audio/pickup.wav"
  crouch: "../../assets/audio/proper_crouch.wav"
  jump: "../../assets/audio/proper_jump.wav"
  rock-smash: "../../assets/audio/proper_rock_smash.wav"
  boom: "../../assets/audio/boom.wav"
  dudum: "../../assets/audio/dudum.wav"
  error: "../../assets/audio/error.wav"
  fart: "../../assets/audio/fart.wav"
  mepmep: "../../assets/audio/mepmep.wav"
  ohje: "../../assets/audio/ohje.wav"
  cool-sound: "../../assets/audio/cool_sound.mp3"
  oof: "../../assets/audio/oof.wav"
  pipe: "../../assets/audio/pipe.wav"
  meme-jump: "../../assets/audio/jump.wav"
  game-over: "../../assets/audio/game_over.wav"
  meme-game-over: "../../assets/audio/gameover.wav"
  meme-game-over2: "../../assets/audio/shutdown.wav"
  nuke: "../../assets/audio/nuke.mp3"
  eat: "../../assets/audio/eat.mp3"
  rock-terrain_smash: "../../assets/audio/rock-terrain_smash.mp3"
  moving: "../../assets/audio/moving.mp3"

textures:
  crouch: "../../assets/texture/player_duck.png"
  jump: "../../assets/texture/player_jump.png"
  walk: "../../assets/texture/player_walk.png"
  crouch-shield: "../../assets/texture/player_duck_shield.png"
  jump-shield: "../../assets/texture/player_jump_shield.png"
  walk-shield: "../../assets/texture/player_walk_shield.png"
  kaiserschmarrn: "../../assets/texture/kaiserschmarrn.png"
  coin: "../../assets/texture/coin.png"
  duck: "../../assets/texture/duck.png"
  bomb: "../../assets/texture/rock_bomb.png"
  rock: "../../assets/texture/stone.png"
  explosion: "../../assets/texture/explosion.png"
  helicopter: "../../assets/texture/helicopter.png"
  monster: "../../assets/texture/killbar.png"
  background: "../../assets/layers/mountainBackground.png"
  mountain: "../../assets/layers/mountain3.png"
  startScreen: "../../assets/screens/start_screen.png"
  controlsScreen: "../../assets/screens/controls_screen.png"
  endScreen: "../../assets/screens/end_screen.png"
  instructionScreen: "../../assets/screens/instructions_screen.png"
  pauseScreen: "../../assets/screens/pause_screen.png"
  settingsButton: "../../assets/screens/buttons/settings.png"
  settingsButtonToggled: "../../assets/screens/buttons/settings_toggled.png"
  instructionsButton: "../../assets/screens/buttons/instructions.png"
  instructionsButtonToggled: "../../assets/screens/buttons/instructions_toggled.png"
  startButton: "../../assets/screens/buttons/start_game.png"
  startButtonToggled: "../../assets/screens/buttons/start_game_toggled.png"
  continueButton: "../../assets/screens/buttons/continue_game.png"
  continueButtonToggled: "../../assets/screens/buttons/continue_game_toggled.png"
  playAgainButton: "../../assets/screens/buttons/play_again.png"
  playAgainButtonToggled: "../../assets/screens/buttons/play_again_toggled.png"
  homeButton: "../../assets/screens/buttons/home_button.png"
  homeButtonToggled: "../../assets/screens/buttons/home_button_toggled.png"
  backToMenuButton: "../../assets/screens/buttons/back_to_menu.png"
  backToMenuButtonToggled: "../../assets/screens/buttons/back_to_menu_toggled.png"
  closeGameButton: "../../assets/screens/buttons/close_game.png"
  closeGameButtonToggled: "../../assets/screens/buttons/close_game_toggled.png"
  rockRectangle: "../../assets/texture/rock.png"
  lavaRock: "../../assets/texture/lavaRock.png"
  iceRock: "../../assets/texture/iceRock.png"
  heavyRock: "../../assets/texture/heavyRock.png"
  snowRock: "../../assets/texture/snowRock.png"
  crystalRock: "../../assets/texture/crystalRock.png"
  default: "../../assets/texture/default.png"
  scoreBgX: "../../assets/texture/scoreBgX.png"
  scoreBgY: "../../assets/texture/scoreBgY.png"
  terrainGenerationBackground: "../../assets/texture/terrainGenerationBackground.png"
  recognizeGamepadBackground: "../../assets/texture/recognizeGamepadBackground.png"

items:
  kaiserschmarrn:
    typeId: 0
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 2
  coin:
    typeId: 1
    autoCollect: true
    useOnPickUp: true
    dropOnUse: true
    spawnWeight: 6
  duck:
    typeId: 2
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 2
  bomb:
    typeId: 3
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 1

landmarks:
  - name: "Statue of Liberty"
    height: 93
  - name: "Big Ben"
    height: 96
  - name: "Eiffel Tower"
    height: 300
  - name: "Mount Everest"
    height: 8849

gameConstants:
  hikerConstants:
    hikerMaxHealth: 100
    spawnXRelativeToScreenWidth: 0.4
    hikerHeight: 1.8
    hikerWidth: 1.15
    crouchedHikerHeight: 1.42
    crouchedHikerWidth: 0.96
    mass: 800.0
    duckSpeedFactor: 0.35
    normalSpeed: 5.0
    maxSpeed: 13.0 # Make sure this times airMovementSpeedFactor is higher than maxKillBarVelocity
    jumpVelocity: 10.0
    airMovementSpeedFactor: 0.77
    maxSpeedFactorNegSlope: 1.5 # This is actually a factor ;)
    maxClimbableSlope: 4.0
    knockbackIntensity: 0.5 # between 0 and 1
    knockbackLossPerStep: 0.25 # between 0 and 1
    knockbackCutoff: 5

  itemsConstants:
    spawnItems: true
    shieldTime: 15.0
    collectionRadius: 1.0
    slotsPerInventory: 3
    itemsPerSlot: 64
    kaiserschmarrnHealthRestoration: 30
    coinScore: 500
    coinAccelerationFactor: 0.05
    startSpawnTime: 5.0
    minSpawnTime: 1
    maxSpawnTime: 2
    itemBaseSpawnHeight: 1
    itemMaxSpawnHeight: 2.6
    inventorySlotSize: 80.0

  rockConstants:
    spawnRocks: true
    minRockSize: 0.32
    maxRockSize: 1.0
    minSpawnLinearMomentum: 0.01
    maxSpawnLinearMomentum: 10.0
    minSpawnAngularMomentum: 0.1
    maxSpawnAngularMomentum: 1.0
    spawnOffsetX: 0.5
    minRockDensity: 1.0
    maxRockDensity: 3.0

  physicsConstants:
    gravitationalConstant: -9.81
    gravitySpinEffectOnVertices: 0.05
    epsilon: 0.01 # should be "small"
    rockRockBounciness: 0.4 # between 0 and 1 (wink wink*)
    rockTerrainBounciness: 0.9 #between 0 and 1 (wink wink*)
    physicsDeltaT: 0.015 # ideally, 1/physicsDeltaT >> frameRate
    maxNumberOfResolutionSteps: 4
    maxNumberOfPhysicsStepsPerFrame: 10
    terrainSubstepSize: 0.5 # between 0 and 1 (no seriously this time)
    rockSubstepSize: 0.5 # between 0 and 1 (no seriously this time)
    debugCDRendering: false
    #staticFriction: 0.6
    #dynamicFriction: 0.2

  inputConstants:
    maxGamepads: 8
    gamepadItemSwitchCooldown: 0.1
    gamepadInitializingTime: 0
    gamepadInitializingCountdownFontSize: 120
    itemSwitchThreshold: 0.5

  visualConstants:
    uiMargin: 20
    fontSizeScore: 30
    fontSizeAltimeter: 20
    healthBarWidth: 200
    healthBarHeight: 20
    positionToScoreRatio: 10
    altimeterSteps: 10
    rumbleIntensity: 0.3 # between 0 and 1, 1 meaning full intensity
    rumbleDampening: 0.1 # between 0 and 1, 1 meaning no dampening
    backgroundDistanceScale: 0.1
    cameraToHikerOffset: 1
    mountainGradientHeight: 300
    mountainResolution: 10
    shakeEnabled: true
    renderPhysicsStepSize: false
    worldSize: 35 # The amount of terrain that is rendered in the world in meters

  audioConstants:
    musicEnabled: true
    musicVolume: 0.3
    effectsThreshold: 25

  barriersConstants:
    killBarBaseVelocity: 2.0
    killBarAccelerationFactor: 1.0001 # describes how quickly the killbar accelerates
    killBarMaxVelocity: 7.0 # make sure the hiker max speed is a bit higher than this.
    playerRightBarrierOffset: 15.0
    monsterXRelativeToScreenWidth: 0.1
    monsterHeight: 3.6
    monsterWidth: 2.875

  terrainConstants:
    bufferLeft: 25.0
    bufferRight: 50.0
    biomeWidth: 100.0

    renderingResolution: 0.1
    collisionDetectionResolution: 1
    collisionDetectionPreFilteringTolerance: 0.2

    generationCheckingRange: 5.0
    minimalBasePointDistance: 1.0
    minimalBasePolylineAngle: 30.0 #in degrees
    maximalSlopeHikerClearance: 85.0 #in degrees
    hikerClearanceTolerance: 1.5 #multiplier for hiker width and height
    maximalOverhangDepth: 7.0
    maximalOverhangHeight: 5.0

  rockSpawnerConstants:
    maxNumberOfRocksToSpawn: 3
    # All based on difficulty [EEEASY, EASY, MEDIUM, HARD, I_WANT_MOMY]
    linearMomentumDifficultyFactor: [ 0.0, 0.25, 0.5, 0.75, 1.0 ]
    spawningPhase: [ 60.0, 150.0, 250.0, 500.0, 1000.0 ]
    rockSpawnTimeInterval: [ 8.0, 7.0, 5.0, 3.0, 2.0 ]

    # Based on rock type
    rockTypePhase: [ 30.0, 40.0, 50.0, 60.0, 70.0, 80.0 ]

    #other constants
    minAngularMomentum: -0.5
    maxAngularMomentum: 1.0
    minNumPointsForGeneration: 50
    maxNumPointsForGeneration: 200
    minRandYSpawnOffset: 6
    maxRandYSpawnOffset: 8

  difficultyConstants:
    highesDifficultyLevel: 5 # The highest level possible
    difficultyFactor: 20 # The size of the time step between the different levels
    difficultyStartingPoint: 15 # The starting point at which level 1 starts (levels start at 0)

# flat, exponential steps
# ground-points: [[-100, 0], [-20, 0], [-10,0], [-5, 0], [-1, 0], [-0.5, 0], [0, 0], [0.5, 0], [1, 0], [5, 0], [10, 0], [20, 0], [100, 0]] #flat

# flat small steps
#ground-points:
#  [[-30, 0],[-29, 0],[-28, 0],[-27, 0],[-26, 0],[-25, 0],[-24, 0],[-23, 0],[-22, 0],[-21, 0],[-20, 0],[-19, 0],[-18, 0],[-17, 0],[-16, 0],[-15, 0],[-14, 0],[-13, 0],[-12, 0],[-11, 0],[-10, 0],[-9, 0],[-8, 0],[-7, 0],[-6, 0],[-5, 0],[-4, 0],[-3, 0],[-2, 0],[-1, 0],[0, 0],[1, 0],[2, 0],[3, 0],[4, 0],[5, 0],[6, 0],[7, 0],[8, 0],[9, 0],[10, 0],[11, 0],[12, 0],[13, 0],[14, 0],[15, 0],[16, 0],[17, 0],[18, 0],[19, 0],[20, 0],[21, 0],[22, 0],[23, 0],[24, 0],[25, 0],[26, 0],[27, 0],[28, 0],[29, 0],[30, 0]]

# buggy hill
ground-points: [ [ -100, 0 ], [ -10, 0 ], [ 0, 7 ], [ 3, 7 ], [ 4.7, 7 ], [ 7, 5 ], [ 9, 5 ],  [ 10, 4.2 ], [ 5.5, 4 ], [ 7.5, 3 ], [ 8, 2 ], [ 9, 1 ], [ 10, 0 ], [ 20, 0 ] ]

  # buggy 2
  #ground-points: [[-100, 0], [0, 0], [2.6, 1.6], [2.7, -2.25], [10, 0], [100, 0]]

  # inverse triangle
  #ground-points: [[-30, 30], [-29, 29], [-28, 28], [-27, 27], [-26, 26], [-25, 25], [-24, 24], [-23, 23], [-22, 22], [-21, 21], [-20, 20], [-19, 19], [-18, 18], [-17, 17], [-16, 16], [-15, 15], [-14, 14], [-13, 13], [-12, 12], [-11, 11], [-10, 10], [-9, 9], [-8, 8], [-7, 7], [-6, 6], [-5, 5], [-4, 4], [-3, 3], [-2, 2], [-1, 1], [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10], [11, 11], [12, 12], [13, 13], [14, 14], [15, 15], [16, 16], [17, 17], [18, 18], [19, 19], [20, 20], [21, 21], [22, 22], [23, 23], [24, 24], [25, 25], [26, 26], [27, 27], [28, 28], [29, 29], [30, 30]]

  # simple bowl
  #ground-points: [[-30, 100], [-29, 95], [-28, 90], [-27, 85], [-26, 80], [-25, 75], [-24, 70], [-23, 65], [-22, 60], [-21, 55], [-20, 50], [-19, 45], [-18, 40], [-17, 35], [-16, 30], [-15, 25], [-14, 20], [-13, 15], [-12, 10], [-11, 5], [-10, 0], [-9, 0], [-8, 0], [-7, 0], [-6, 0], [-5, 0], [-4, 0], [-3, 0], [-2, 0], [-1, 0], [0, 0], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [6, 0], [7, 0], [8, 0], [9, 0], [10, 0], [11, 5], [12, 10], [13, 15], [14, 20], [15, 25], [16, 30], [17, 35], [18, 40], [19, 45], [20, 50], [21, 55], [22, 60], [23, 65], [24, 70], [25, 75], [26, 80], [27, 85], [28, 90], [29, 95], [30, 100]]

  # quadratic bowl
#ground-points: [[-25, 100], [-24, 92.16], [-23, 84.64], [-22, 77.44], [-21, 70.56], [-20, 64.00], [-19, 57.76], [-18, 51.84], [-17, 46.24], [-16, 40.96], [-15, 36.00], [-14, 31.36], [-13, 27.04], [-12, 23.04], [-11, 19.36], [-10, 16.00], [-9, 12.96], [-8, 10.24], [-7, 7.84], [-6, 5.76], [-5, 4.00], [-4, 2.56], [-3, 1.44], [-2, 0.64], [-1, 0.16], [0, 0], [1, 0.16], [2, 0.64], [3, 1.44], [4, 2.56], [5, 4.00], [6, 5.76], [7, 7.84], [8, 10.24], [9, 12.96], [10, 16.00], [11, 19.36], [12, 23.04], [13, 27.04], [14, 31.36], [15, 36.00], [16, 40.96], [17, 46.24], [18, 51.84], [19, 57.76], [20, 64.00], [21, 70.56], [22, 77.44], [23, 84.64], [24, 92.16], [25, 100]]
