run-dev-mode: true # if true the manual tests will run instead of the normal game
fullscreen: true

music:
  background-music: "../../assets/audio/happy-funny-kids.mp3"
  background-music2: "../../assets/audio/background_music2.wav"

soundEffects:
  use-kaiserschmarrn: "../../assets/audio/cool_sound.mp3"
  use-duck: "../../assets/audio/duck.wav"
  use-coin: "../../assets/audio/proper_coin.wav"
  pickup-item: "../../assets/audio/pickup.wav"
  crouch: "../../assets/audio/proper_crouch.wav"
  jump: "../../assets/audio/proper_jump.wav"
  rock-smash: "../../assets/audio/proper_rock_smash.wav"
  boom: "../../assets/audio/boom.wav"
  dudum: "../../assets/audio/dudum.wav"
  error: "../../assets/audio/error.wav"
  fart: "../../assets/audio/fart.wav"
  mepmep: "../../assets/audio/mepmep.wav"
  ohje: "../../assets/audio/ohje.wav"
  cool-sound: "../../assets/audio/cool_sound.mp3"
  oof: "../../assets/audio/oof.wav"
  pipe: "../../assets/audio/pipe.wav"
  meme-jump: "../../assets/audio/jump.wav"
  game-over: "../../assets/audio/game_over.wav"
  meme-game-over: "../../assets/audio/gameover.wav"
  meme-game-over2: "../../assets/audio/shutdown.wav"
  nuke: "../../assets/audio/nuke.mp3"
  eat: "../../assets/audio/eat.mp3"
  rock-terrain_smash: "../../assets/audio/rock-terrain_smash.mp3"
  moving: "../../assets/audio/moving.mp3"

textures:
  crouch: "../../assets/texture/player_duck.png"
  jump: "../../assets/texture/player_jump.png"
  walk: "../../assets/texture/player_walk.png"
  crouch-shield: "../../assets/texture/player_duck_shield.png"
  jump-shield: "../../assets/texture/player_jump_shield.png"
  walk-shield: "../../assets/texture/player_walk_shield.png"
  kaiserschmarrn: "../../assets/texture/kaiserschmarrn.png"
  coin: "../../assets/texture/coin.png"
  duck: "../../assets/texture/duck.png"
  bomb: "../../assets/texture/rock_bomb.png"
  rock: "../../assets/texture/stone.png"
  explosion: "../../assets/texture/explosion.png"
  helicopter: "../../assets/texture/helicopter.png"
  monster: "../../assets/texture/killbar.png"
  background: "../../assets/layers/mountainBackground.png"
  mountain: "../../assets/layers/mountain3.png"
  startScreen: "../../assets/screens/start_screen.png"
  controlsScreen: "../../assets/screens/controls_screen.png"
  endScreen: "../../assets/screens/end_screen.png"
  instructionScreen: "../../assets/screens/instructions_screen.png"
  pauseScreen: "../../assets/screens/pause_screen.png"
  settingsButton: "../../assets/screens/buttons/settings.png"
  settingsButtonToggled: "../../assets/screens/buttons/settings_toggled.png"
  instructionsButton: "../../assets/screens/buttons/instructions.png"
  instructionsButtonToggled: "../../assets/screens/buttons/instructions_toggled.png"
  startButton: "../../assets/screens/buttons/start_game.png"
  startButtonToggled: "../../assets/screens/buttons/start_game_toggled.png"
  continueButton: "../../assets/screens/buttons/continue_game.png"
  continueButtonToggled: "../../assets/screens/buttons/continue_game_toggled.png"
  playAgainButton: "../../assets/screens/buttons/play_again.png"
  playAgainButtonToggled: "../../assets/screens/buttons/play_again_toggled.png"
  homeButton: "../../assets/screens/buttons/home_button.png"
  homeButtonToggled: "../../assets/screens/buttons/home_button_toggled.png"
  backToMenuButton: "../../assets/screens/buttons/back_to_menu.png"
  backToMenuButtonToggled: "../../assets/screens/buttons/back_to_menu_toggled.png"
  closeGameButton: "../../assets/screens/buttons/close_game.png"
  closeGameButtonToggled: "../../assets/screens/buttons/close_game_toggled.png"
  rockRectangle: "../../assets/texture/rock.png"
  lavaRock: "../../assets/texture/lavaRock.png"
  iceRock: "../../assets/texture/iceRock.png"
  heavyRock: "../../assets/texture/heavyRock.png"
  snowRock: "../../assets/texture/snowRock.png"
  crystalRock: "../../assets/texture/crystalRock.png"
  default: "../../assets/texture/default.png"
  scoreBgX: "../../assets/texture/scoreBgX.png"
  scoreBgY: "../../assets/texture/scoreBgY.png"
  terrainGenerationBackground: "../../assets/texture/terrainGenerationBackground.png"
  recognizeGamepadBackground: "../../assets/texture/recognizeGamepadBackground.png"

items:
  kaiserschmarrn:
    typeId: 0
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 2
  coin:
    typeId: 1
    autoCollect: true
    useOnPickUp: true
    dropOnUse: true
    spawnWeight: 6
  duck:
    typeId: 2
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 2
  bomb:
    typeId: 3
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 1

landmarks:
  - name: "Mariana Trench"
    height: -10994
  - name: "Statue of Liberty"
    height: 93
  - name: "Big Ben"
    height: 96
  - name: "Eiffel Tower"
    height: 300
  - name: "Rittner Horn"
    height: 2270
  - name: "Großer Ifinger"
    height: 2581
  - name: "Hirzer"
    height: 2781
  - name: "Mount Everest"
    height: 8849

gameConstants:
  hikerConstants:
    hikerMaxHealth: 300
    spawnXRelativeToScreenWidth: 0.4
    hikerSize: 1.8
    hikerSizeRatio: 0.7
    hikerCrouchRatio: 0.8
    mass: 800.0
    duckSpeedFactor: 0.35
    normalSpeed: 5.0
    maxSpeed: 13.0 # Make sure this times airMovementSpeedFactor is higher than maxKillBarVelocity
    jumpVelocity: 10.0
    airMovementSpeedFactor: 0.77
    maxSpeedFactorNegSlope: 1.5 # This is actually a factor ;)
    maxClimbableSlope: 4.0
    knockbackIntensity: 0.5 # between 0 and 1
    knockbackLossPerStep: 0.25 # between 0 and 1
    knockbackCutoff: 5

  itemsConstants:
    spawnItems: true
    shieldTime: 15.0
    collectionRadius: 1.0
    slotsPerInventory: 3
    itemsPerSlot: 64
    kaiserschmarrnHealthRestoration: 0.2 # restores percentage of max health
    coinScore: 500
    coinAccelerationFactor: 0.05
    startSpawnTime: 5.0
    minSpawnTime: 3
    maxSpawnTime: 10
    itemBaseSpawnHeight: 1
    itemMaxSpawnHeight: 2.6
    inventorySlotSize: 80.0

  rockConstants:
    spawnRocks: true
    minRockSize: 0.32
    maxRockSize: 1.0
    spawnOffsetX: 0.5
    minRockDensity: 1.0
    maxRockDensity: 3.0

  physicsConstants:
    gravitationalConstant: -9.81
    gravitySpinEffectOnVertices: 0.05
    epsilon: 0.01 # should be "small"
    rockRockBounciness: 0.2 # between 0 and 1 (wink wink*)
    rockTerrainBounciness: 0.85 #between 0 and 1 (wink wink*)
    physicsDeltaT: 0.015 # ideally, 1/physicsDeltaT >> frameRate
    maxNumberOfResolutionSteps: 4
    maxNumberOfPhysicsStepsPerFrame: 10
    terrainSubstepSize: 0.5 # between 0 and 1 (no seriously this time)
    rockSubstepSize: 0.5 # between 0 and 1 (no seriously this time)
    debugCDRendering: true
    #staticFriction: 0.6
    #dynamicFriction: 0.2

  inputConstants:
    maxGamepads: 8
    gamepadItemSwitchCooldown: 0.1
    gamepadInitializingTime: 5
    gamepadInitializingCountdownFontSize: 120
    itemSwitchThreshold: 0.5

  visualConstants:
    uiMargin: 20
    fontSizeScore: 30
    fontSizeAltimeter: 20
    healthBarWidth: 250
    healthBarHeight: 20
    positionToScoreRatio: 10
    altimeterSteps: 10
    rumbleIntensity: 0.3 # between 0 and 1, 1 meaning full intensity
    rumbleDampening: 0.1 # between 0 and 1, 1 meaning no dampening
    backgroundDistanceScale: 0.1
    cameraToHikerOffset: 1
    mountainGradientHeight: 300
    mountainResolution: 10
    shakeEnabled: true
    renderPhysicsStepSize: false
    worldSize: 35 # The amount of terrain that is rendered in the world in meters

  audioConstants:
    musicEnabled: true
    musicVolume: 0.3
    effectsThreshold: 25

  barriersConstants:
    killBarBaseVelocity: 2.0
    killBarAccelerationFactor: 1.0001 # describes how quickly the killbar accelerates
    killBarMaxVelocity: 7.0 # make sure the hiker max speed is a bit higher than this.
    playerRightBarrierOffset: 15.0
    monsterXRelativeToScreenWidth: 0.1
    monsterHeight: 3.6
    monsterWidth: 2.875

  terrainConstants:
    bufferLeft: 25.0
    bufferRight: 50.0
    biomeWidth: 100.0

    renderingResolution: 0.1
    collisionDetectionResolution: 1
    collisionDetectionPreFilteringTolerance: 0.2

    generationCheckingRange: 5.0
    minimalBasePointDistance: 1.0
    minimalBasePolylineAngle: 30.0 #in degrees
    maximalSlopeHikerClearance: 85.0 #in degrees
    hikerClearanceTolerance: 1.5 #multiplier for hiker width and height
    maximalOverhangDepth: 7.0
    maximalOverhangHeight: 5.0

  rockSpawnerConstants:
    maxNumberOfRocksToSpawn: 3
    # All based on difficulty [EEEASY, EASY, MEDIUM, HARD, I_WANT_MOMY]
    linearMomentumDifficultyFactor: [ 0.0, 0.25, 0.5, 0.75, 1.0 ]
    spawningPhase: [ 60.0, 150.0, 250.0, 500.0, 1000.0 ]
    rockSpawnTimeInterval: [ 8.0, 7.0, 5.0, 3.0, 2.0 ]

    # Based on rock type
    rockTypePhase: [ 30.0, 40.0, 50.0, 60.0, 70.0, 80.0 ]

    #other constants
    minAngularMomentum: -2
    maxAngularMomentum: 8
    minLinearMomentum: 0.01
    maxLinearMomentum: 10.0
    minNumPointsForGeneration: 50
    maxNumPointsForGeneration: 200
    minRandYSpawnOffset: 6
    maxRandYSpawnOffset: 8

  difficultyConstants:
    highesDifficultyLevel: 5 # The highest level possible
    difficultyFactor: 60 # The size of the time step between the different levels
    difficultyStartingPoint: 60 # The starting point at which level 1 starts (levels start at 0)