run-dev-mode: false # if true the manual tests will run instead of the normal game

soundEffects:
  background-music: "../../assets/audio/background_music.mp3"
  background-music2: "../../assets/audio/background_music2.wav"
  use-kaiserschmarrn: "../../assets/audio/cool_sound.mp3"
  use-duck: "../../assets/audio/duck.wav"
  use-coin: "../../assets/audio/proper_coin.wav"
  pickup-item: "../../assets/audio/pickup.wav"
  crouch: "../../assets/audio/proper_crouch.wav"
  jump: "../../assets/audio/proper_jump.wav"
  rock-smash: "../../assets/audio/proper_rock_smash.wav"
  boom: "../../assets/audio/boom.wav"
  dudum: "../../assets/audio/dudum.wav"
  error: "../../assets/audio/error.wav"
  fart: "../../assets/audio/fart.wav"
  mepmep: "../../assets/audio/mepmep.wav"
  ohje: "../../assets/audio/ohje.wav"
  cool-sound: "../../assets/audio/cool_sound.mp3"
  oof: "../../assets/audio/oof.wav"
  pipe: "../../assets/audio/pipe.wav"
  meme-jump: "../../assets/audio/jump.wav"
  game-over: "../../assets/audio/game_over.wav"
  meme-game-over: "../../assets/audio/gameover.wav"
  meme-game-over2: "../../assets/audio/shutdown.wav"

textures:
  crouch: "../../assets/texture/player_duck.png"
  jump: "../../assets/texture/player_jump.png"
  walk: "../../assets/texture/player_walk.png"
  crouch-shield: "../../assets/texture/hiker_duck.png"
  jump-shield: "../../assets/texture/hiker_jump.png"
  walk-shield: "../../assets/texture/hiker_walk.png"
  kaiserschmarrn: "../../assets/texture/kaiserschmarrn.png"
  coin: "../../assets/texture/coin.png"
  duck: "../../assets/texture/duck.png"
  rock: "../../assets/texture/stone.png"
  explosion: "../../assets/texture/explosion.png"
  helicopter: "../../assets/texture/helicopter.png"
  monster: "../../assets/texture/killbar.png"
  midground: "../../assets/layers/mountainBackground.png"
  foreground: "../../assets/layers/clouds_mg_1.png"
  mountain: "../../assets/layers/mountain3.png"
  startScreen: "../../assets/screens/start_screen.png"
  settingsScreen: "../../assets/screens/settings_screen.png"
  endScreen: "../../assets/screens/end_screen.png"
  instructionScreen: "../../assets/screens/instructions_screen.png"
  pauseScreen: "../../assets/screens/pause_screen.png"
  settingsButton: "../../assets/screens/buttons/settings.png"
  settingsButtonToggled: "../../assets/screens/buttons/settings_toggled.png"
  instructionsButton: "../../assets/screens/buttons/instructions.png"
  instructionsButtonToggled: "../../assets/screens/buttons/instructions_toggled.png"
  startButton: "../../assets/screens/buttons/start_game.png"
  startButtonToggled: "../../assets/screens/buttons/start_game_toggled.png"
  continueButton: "../../assets/screens/buttons/continue_game.png"
  continueButtonToggled: "../../assets/screens/buttons/continue_game_toggled.png"
  playAgainButton: "../../assets/screens/buttons/play_again.png"
  playAgainButtonToggled: "../../assets/screens/buttons/play_again_toggled.png"
  homeButton: "../../assets/screens/buttons/home_button.png"
  homeButtonToggled: "../../assets/screens/buttons/home_button_toggled.png"
  backToMenuButton: "../../assets/screens/buttons/back_to_menu.png"
  backToMenuButtonToggled: "../../assets/screens/buttons/back_to_menu_toggled.png"
  closeGameButton: "../../assets/screens/buttons/close_game.png"
  closeGameButtonToggled: "../../assets/screens/buttons/close_game_toggled.png"
  rockRectangle: "../../assets/texture/rock.png"
  lavaRock: "../../assets/texture/lavaRock.png"
  iceRock: "../../assets/texture/iceRock.png"
  heavyRock: "../../assets/texture/heavyRock.png"
  snowRock: "../../assets/texture/snowRock.png"
  crystalRock: "../../assets/texture/crystalRock.png"
  default: "../../assets/texture/default.png"
  terrainGenerationBackground: "../../assets/texture/terrainGenerationBackground.png"

items:
  kaiserschmarrn:
    typeId: 0
    autoCollect: false
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 2
  coin:
    typeId: 1
    autoCollect: true
    useOnPickUp: true
    dropOnUse: true
    spawnWeight: 6
  duck:
    typeId: 2
    autoCollect: true
    useOnPickUp: false
    dropOnUse: true
    spawnWeight: 2

landmarks:
  - name: "Statue of Liberty"
    height: 93
  - name: "Big Ben"
    height: 96
  - name: "Eiffel Tower"
    height: 300
  - name: "Mount Everest"
    height: 8849

gameConstants:
  hikerConstants:
    hikerMaxHealth: 100
    hikerHeight: 1.8
    hikerWidth: 1.15
    crouchedHikerHeight: 1.42
    crouchedHikerWidth: 0.96
    mass: 800.0
    duckSpeedFactor: 0.35
    normalSpeed: 2.6
    jumpVelocity: 10.0
    airMovementSpeedFactor: -0.6
    knockBack: 0.00005
    maxSpeedNegSlope: 5.0
    maxClimbableSlope: 4.0
    terrainCollisionDampening: 0.8
    friction: 0.3 #is applied to the gravitational constant, when the hiker slides down the terrain

  itemsConstants:
    spawnItems: true
    shieldTime: 5.0
    collectionRadius: 1.0
    slotsPerInventory: 3
    itemsPerSlot: 64
    kaiserschmarrnHealthRestoration: 30
    coinScore: 500
    startSpawnTime: 5.0
    minSpawnTime: 2
    maxSpawnTime: 10
    itemBaseHeight: 1
    itemMaxHeight: 2.6
    itemsPerSecond: 0.05
    inventorySlotSize: 80.0

  rockConstants:
    spawnRocks: true
    minRockSize: 0.32
    maxRockSize: 1.0
    velocityCap: 1200.0
    gamma: 1.0
    maxAngularVelocity: 1.0
    minSpawnVelocity: 0.01
    maxSpawnVelocity: 10.0
    minSpawnRotationVelocity: 0.1
    maxSpawnRotationVelocity: 1.0
    rockTimePeriodDifficult: 1.0
    rockTimePeriodMedium: 5.0
    rockTimePeriodEasy: 2.0
    timeBetweenRockSpawns: 5.0
    numOfRocksToSpawn: 10
    spawnOffsetX: 0.5
    minRockDensity: 1.0
    maxRockDensity: 3.0

  physicsConstants:
    gravitationalConstant: -9.81
    epsilon: 0.001
    rockTerrainDamping: 0.08
    physicsDeltaT: 0.01

  inputConstants:
    maxGamepads: 8

  visualConstants:
    uiMargin: 20
    fontSizeScore: 30
    fontSizeAltimeter: 20
    healthBarWidth: 200
    healthBarHeight: 20
    positionToScoreRatio: 10
    altimeterSteps: 10
    rumbleIntensity: 0.4
    rumbleDampening: 0.9
    textureMidScale: 1.0
    textureForeScale: 7.0
    cameraToHikerOffset: 1
    mountainGradientHeight: 300
    mountainResolution: 10

  barriersConstants:
    killBarVelocity: 1.0
    playerRightBarrierOffset: 15.0

  mountainConstants:
    visibleChunksCount: 16
    chunkBufferLeft: 2
    chunkBufferRight: 16
    initialHeight: 0
    slope: 0.4
    randomness: 1.0
    linStepSize: 0.5

  terrainConstants:
    bufferLeft: 25.0
    bufferRight: 25.0
    biomeWidth: 100.0

    renderingResolution: 0.1
    collisionDetectionResolution: 0.1
    collisionDetectionPreFilteringTolerance: 0.2

    generationCheckingRange: 5.0
    minimalBasePointDistance: 1.0
    minimalBasePolylineAngle: 30.0 #in degrees
    maximalSlopeHikerClearance: 85.0 #in degrees
    hikerClearanceTolerance: 1.5 #multiplier for hiker width and height
    maximalOverhangDepth: 7.0
    maximalOverhangHeight: 5.0

  rockSpawnerConstants:
    # All based on difficulty [EEEASY, EASY, MEDIUM, HARD, I_WANT_MOMY]
    velocityDifficultyFactor: [ 0.0, 0.25, 0.5, 0.75, 1.0 ]
    spawningPhase: [ 60.0, 150.0, 250.0, 500.0, 1000.0 ]
    rockSpawnTimeInterval: [ 8.0, 7.0, 5.0, 3.0, 2.0 ]

    # Based on rock type
    rockTypePhase: [ 30.0, 40.0, 50.0, 60.0, 70.0, 80.0 ]