soundEffects:
  background-music: "../assets/audio/background_music.mp3"
  background-music2: "../assets/audio/background_music2.wav"
  use-kaiserschmarrn: "../assets/audio/cool_sound.mp3"
  use-duck: "../assets/audio/duck.wav"
  use-coin: "../assets/audio/proper_coin.wav"
  pickup-item: "../assets/audio/pickup.wav"
  crouch: "../assets/audio/proper_crouch.wav"
  jump: "../assets/audio/proper_jump.wav"
  rock-smash: "../assets/audio/proper_rock_smash.wav"
  boom: "../assets/audio/boom.wav"
  dudum: "../assets/audio/dudum.wav"
  error: "../assets/audio/error.wav"
  fart: "../assets/audio/fart.wav"
  mepmep: "../assets/audio/mepmep.wav"
  ohje: "../assets/audio/ohje.wav"
  cool-sound: "../assets/audio/cool_sound.mp3"
  oof: "../assets/audio/oof.wav"
  pipe: "../assets/audio/pipe.wav"
  meme-jump: "../assets/audio/jump.wav"
  game-over: "../assets/audio/game_over.wav"
  meme-game-over: "../assets/audio/gameover.wav"
  meme-game-over2: "../assets/audio/shutdown.wav"

textures:
  crouch: "../assets/texture/player_duck.png"
  jump: "../assets/texture/player_jump.png"
  walk: "../assets/texture/player_walk.png"
  Kaiserschmarrn: "../assets/texture/kaiserschmarrn.png"
  Coin: "../assets/texture/coin.png"
  Duck: "../assets/texture/duck.png"
  rock: "../assets/texture/stone.png"
  explosion: "../assets/texture/explosion.png"
  helicopter: "../assets/texture/helicopter.png"
  monster: "../assets/texture/killbar.png"
  midground: "../assets/layers/glacial_mountains.png"
  foreground: "../assets/layers/clouds_mg_1.png"
  mountain: "../assets/layers/mountain.png"
